name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
   
     

    - name: Create Build Directory
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: mkdir ${{runner.workspace}}/build
         
     
     
     
     
     
    - name: Current Working directory
      working-directory: ${{runner.workspace}}/build 
      run: pwd
     
     
     
     
     
    - name: Create Open cv directory
      working-directory: ${{runner.workspace}}/build
      run: mkdir opencv
    
     
     
    - name: change directory 
      run: cd ${{runner.workspace}}/build/opencv
           
    - name: List contents of working dir
      working-directory:  ${{runner.workspace}}/build     
      run: ls -ltr
   
   
   
    - name: Change to current working directory
      shell: bash
      run: cd ${{runner.workspace}}/build/opencv
   
    
    
    
    - name: Create CMakeLists.txt 
      shell: bash
      run: touch CMakeLists.txt
     
     
     
     
    #- name: Install Open CV for Computer Vision artifacts
    # shell: bash
     # working-directory: cd ${{runner.workspace}}/build/opencv 
     # run: sudo apt install libopencv-dev python3-opencv
          
          
          
    - name: Run Cmake in Build environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake ${{runner.workspace}}/build/opencv -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cd  ${{runner.workspace}}/build
           cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C $BUILD_TYPE
